INSERT INTO PROFESSOR(ano_ingresso,area,curso,link_curriculo,matricula,nome,sobrenome,titulacao) VALUES (2001,'Biologia','SI','www.seila.com.br','20190594','Ana','Pacheco','LICENCIATURA')
INSERT INTO PROFESSOR(ano_ingresso,area,curso,link_curriculo,matricula,nome,sobrenome,titulacao) VALUES (2002,'Matemática','SI','www.seila.com.br','20190674','Maria','Lisboa','LICENCIATURA')
INSERT INTO PROFESSOR(ano_ingresso,area,curso,link_curriculo,matricula,nome,sobrenome,titulacao) VALUES (2003,'Engenharia Mecânica','SI','www.seila.com.br','2020694','João','Carlos','BACHARELADO')
INSERT INTO PROFESSOR(ano_ingresso,area,curso,link_curriculo,matricula,nome,sobrenome,titulacao) VALUES (2004,'Design','SI','www.seila.com.br','20140694','Raimunddo','Oswaldo','LICENCIATURA')
INSERT INTO PROFESSOR(ano_ingresso,area,curso,link_curriculo,matricula,nome,sobrenome,titulacao) VALUES (2005,'Pesquisador','SI','www.seila.com.br','2010684','Selmo','Eduardo','MESTRADO')

INSERT INTO ALUNO (ANO_INGRESSO,MATRICULA,NOME,NOME_CURSO,PERIODO,SOBRENOME) VALUES (2003,'20172SI0203','Pedro','SI',7,'Quisque')
INSERT INTO ALUNO (ANO_INGRESSO,MATRICULA,NOME,NOME_CURSO,PERIODO,SOBRENOME) VALUES (2003,'20172SI0204','Marcio','SI',7,'Roger')
INSERT INTO ALUNO (ANO_INGRESSO,MATRICULA,NOME,NOME_CURSO,PERIODO,SOBRENOME) VALUES (2003,'20172SI0205','Ana','SI',7,'Clara')
INSERT INTO ALUNO (ANO_INGRESSO,MATRICULA,NOME,NOME_CURSO,PERIODO,SOBRENOME) VALUES (2003,'20172SI0206','Lucas','SI',7,'Morim')
INSERT INTO ALUNO (ANO_INGRESSO,MATRICULA,NOME,NOME_CURSO,PERIODO,SOBRENOME) VALUES (2003,'20172SI0207','João','SI',7,'Leão')